jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - continue-on-error: true
      name: Execute Gradle build
      run: ./gradlew check --console=plain --warning-mode all
name: Java CI with Gradle
on:
  repository_dispatch:
    types: trigger-ga___run-build.yml
permissions: read-all
